version: '3.8'

services:
  backend:
    build: ./backend
    container_name: organizacao-financeira-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: sh -c "python create_db.py && flask run --host=0.0.0.0"
    depends_on:
      database: # <-- Alteração aqui
        condition: service_healthy # <-- Alteração aqui

  frontend:
    build: ./frontend
    container_name: organizacao-financeira-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start # <-- Alteração recomendada
    depends_on:
      - backend

  database:
    image: postgres:13-alpine
    container_name: organizacao-financeira-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: organizacao_financeira_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    # Adicione as linhas abaixo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d organizacao_financeira_db"]
      interval: 5s
      timeout: 5s
      retries: 5